spring:
  application:
   name: totaltranslator
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      chat:
        model: ministral-3:3b
  datasource:
    password: admin
    username: admin
    url: jdbc:postgresql://localhost/totaltranslatordb

server:
  port: 12000

springdoc:
  cache:
    disabled: true
  swagger-ui:
    display-request-duration: true
    use-root-path: true
    groups-order: DESC
    operationsSorter: method
  version: 1.0