name: 'total_translator'
services:
 db:
    image: postgres:latest
    container_name: total_translator_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=totaltranslatordb
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"