name: 'vendotudo'
services:
 db:
    image: pgvector/pgvector:pg17
    container_name: vendotudo_vectordb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vendotudo_vectordb
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"