spring:
  application:
   name: comedyclub-mcp
  ai:
    ollama:
      chat:
        model: ministral-3:3b
    mcp:
      client:
        transport: sse
        sse.connections.meucinemaserver.url: http://localhost:20000

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

server:
  port: 11000

springdoc:
  cache:
    disabled: true
  swagger-ui:
    display-request-duration: true
    use-root-path: true
    groups-order: DESC
    operationsSorter: method
  version: 1.0